
# set working directory and load the packages used in the script
setwd("/Users/cabeyrat/Google Drive/Shared drives/DiFazioLab/BESC/BESC_DATA/7x7/Stettler_14_linkage_mapping")
rm(list = ls())
library(dplyr)
library(stringr)
library(lme4)
library(MASS)
library(qvalue)
library(exactci)


# set main input and output paths
par.name.vec <- c("1863", "1909", "1950", "2048", "2066", "2283", "4593", "2365", "2393", "2515", "2572", "2683", "6909", "7073" )
chrom.name.vec <- c( "Chr01", "Chr02", "Chr03", "Chr04", "Chr05", "Chr06", "Chr07", "Chr08", "Chr09", "Chr10", "Chr11", "Chr12", "Chr13", "Chr14", "Chr15", "Chr16", "Chr17", "Chr18", "Chr19")
statistics.input.path <- "./statistics/"
statistics.output.path <- "./statistics/gross_stat_plots/"
sliding.avg.output.path <- "./statistics/heterochiasmy_analysis/sliding_average/"
gen.feat.output.path <- "./genomic_features/analysis_output/"
lg.names <- c("LG-I", "LG-II", "LG-III", "LG-IV", "LG-V", "LG-VI", "LG-VII", "LG-VIII", "LG-IX", "LG-X", "LG-XI", "LG-XII", "LG-XIII", "LG-XIV",
              "LG-XV", "LG-XVI", "LG-XVII", "LG-XVIII", "LG-XIX")

# Read the composite file generated by script S_17b
binned.cos.by.par.df.8 <- read.csv(file = paste0(statistics.input.path, "genomewide_heterochiasmy_final_df2.csv"), header = TRUE, stringsAsFactors = FALSE )
colnames(binned.cos.by.par.df.8) <- colnames(binned.cos.by.par.df.8) %>% str_replace("^X", '')



pdf(file = paste0(statistics.output.path, "genomewide_fine_scale_heterochiasmy.pdf"), width = 8.5, height = 11)
layout(matrix(1:6, nrow=6, byrow=T))
# layout.show(n=6)

margin_points <- data.frame(matrix(c(1,
                   as.numeric(row.names(binned.cos.by.par.df.8[binned.cos.by.par.df.8$CHROM == 'Chr06',])[1]),
                   as.numeric(row.names(binned.cos.by.par.df.8[binned.cos.by.par.df.8$CHROM == 'Chr12',])[1]),
                   
                   as.numeric(row.names(binned.cos.by.par.df.8[binned.cos.by.par.df.8$CHROM == 'Chr06',])[1])-1,
                   as.numeric(row.names(binned.cos.by.par.df.8[binned.cos.by.par.df.8$CHROM == 'Chr12',])[1])-1,
                   nrow(binned.cos.by.par.df.8)), ncol=2, byrow=F), stringsAsFactors=F)
colnames(margin_points) <- c('start', 'end')



# iterating over break-points
for (iter in 1:3) {
  
  # set the first beak-point of the image
  break_point_idxs <- margin_points$start[iter]:margin_points$end[iter]
  
  
  # Plot-1
  op <- par(mar=c(4.1, 5.1, 3.1, 2.1), cex.lab=1.2, cex.axis=1.2, xaxs='i')
  plot(binned.cos.by.par.df.8$WIN.IDX[break_point_idxs], -log10(binned.cos.by.par.df.8$RATE_RATIO[break_point_idxs]), 
       type='h', col='grey57', 
       # xlab='genomic window index', 
       xlab='',
       ylab='-log10(Fem CO / Male CO)')
  
  lines(binned.cos.by.par.df.8$WIN.IDX[binned.cos.by.par.df.8$BH.FDR < 0.25],
        -log10(binned.cos.by.par.df.8$RATE_RATIO[binned.cos.by.par.df.8$BH.FDR < 0.25]), 
        col='blue', type='h', lwd=2)
  lines(binned.cos.by.par.df.8$WIN.IDX[binned.cos.by.par.df.8$BH.FDR < 0.25 & binned.cos.by.par.df.8$RATE_RATIO > 1], 
        -log10(binned.cos.by.par.df.8$RATE_RATIO[binned.cos.by.par.df.8$BH.FDR < 0.25 & binned.cos.by.par.df.8$RATE_RATIO > 1]), col='red', type='h', lwd=2)
  # drawing separatation lines for chromosomes.
  abline(h=0, lty=2, col='grey')
  for (chrom.name in chrom.name.vec) {
    subset.binned.df <- binned.cos.by.par.df.8[binned.cos.by.par.df.8$CHROM == chrom.name, ]
    abline(v=subset.binned.df$WIN.IDX[nrow(subset.binned.df)] ,col='grey', lty=2)
    text(x=subset.binned.df$WIN.IDX[nrow(subset.binned.df)]-6, y=0.3, labels=lg.names[which(chrom.name.vec==chrom.name)])
  }
  par(op)
  
  
  # Plot-2
  # white line plots with the triangular markers at the bottom
  op <- par(mar=c(5.1, 5.1, 0, 2.1), cex.lab=1.2, cex.axis=1.2, xaxs='i')
  for (par.name in par.name.vec[1:14]) { 
    # par.name <- par.name.vec[1]
    colr <- 'white'
    if (par.name == par.name.vec[1]) {
      plot(binned.cos.by.par.df.8$WIN.IDX[break_point_idxs],
           binned.cos.by.par.df.8[break_point_idxs, par.name], col=colr, ylim=c(0, 30), type='l',
           xlab='genomic window index', ylab='cross-over count')
      points(binned.cos.by.par.df.8$WIN.IDX[binned.cos.by.par.df.8$BH.FDR < 0.25],
             rep(0, length(binned.cos.by.par.df.8$WIN.IDX[binned.cos.by.par.df.8$BH.FDR < 0.25])), col='black', pch=17)
    } else {
      lines(binned.cos.by.par.df.8$WIN.IDX, binned.cos.by.par.df.8[, par.name], col=colr)
    }
  }
  
  
  for (chrom.name in chrom.name.vec) { 
    # chrom.name <- chrom.name.vec[1]
    
    # Making the stop gaps for each chromosome
    subset.binned.df <- binned.cos.by.par.df.8[binned.cos.by.par.df.8$CHROM == chrom.name, ]
    splitAt <- function(x, pos) {unname(split(x, cumsum(seq_along(x) %in% pos)))} 
    defined.gap <- 3
    win.indices <- subset.binned.df$WIN.IDX
    idx.diff.vec <- diff(win.indices)
    diff.idx <- which(idx.diff.vec > defined.gap)
    gap.sep.list <- splitAt(win.indices, (diff.idx + 1))
    
    
    for (par.name in par.name.vec) { 
      # par.name <- par.name.vec[1]
      colr <- ifelse(par.name %in% par.name.vec[1:7], yes=rgb(255, 0, 0, max=255, alpha=80, names="red50"), no=rgb(0, 0, 255, max=255, alpha=80, names="blue50"))
      for (l in 1:length(gap.sep.list)) {
        segmnt <- gap.sep.list[[l]]
        tmp.idx <- which(binned.cos.by.par.df.8$WIN.IDX %in% segmnt)
        lines(binned.cos.by.par.df.8$WIN.IDX[tmp.idx], 
              binned.cos.by.par.df.8[tmp.idx, par.name], col=colr, ylim=c(0, 30), type='l', xlab='genomic window index', ylab='cross-over count')
      }
    }
    
    # drawing seapration line for chromosome
    abline(v=subset.binned.df$WIN.IDX[nrow(subset.binned.df)] ,col='grey', lty=2)
    
    # drawing mean line for females & males
    for (l in 1:length(gap.sep.list)) {
      segmnt <- gap.sep.list[[l]]
      tmp.idx <- which(binned.cos.by.par.df.8$WIN.IDX %in% segmnt)
      lines(binned.cos.by.par.df.8$WIN.IDX[tmp.idx], apply(binned.cos.by.par.df.8[tmp.idx, par.name.vec[1:7]], 1, mean, na.rm=TRUE), col='red', lwd=1.5)
      lines(binned.cos.by.par.df.8$WIN.IDX[tmp.idx]+2, apply(binned.cos.by.par.df.8[tmp.idx, par.name.vec[8:14]], 1, mean, na.rm=TRUE), col='blue', lwd=1.5)
    }
  }
  par(op)
}
dev.off()
### END